/*
BlueCat Address Manager 9.5 RESTful v2 API

The **BlueCat Address Manager 9.5 RESTful v2 API** is a new RESTful API for Address Manager that presents Address Manager objects as resources. Each resource has a unique endpoint, and related resources are grouped in collections. To fetch an individual resource, a `GET` request is sent to the resource's endpoint. To fetch all resources in a collection, a `GET` request is sent to the collection's endpoint.  The RESTful v2 API is [hypermedia driven](https://en.wikipedia.org/wiki/HATEOAS) and uses the [HAL](https://en.wikipedia.org/wiki/Hypertext_Application_Language) format for representing links. When navigating through the API, you can use those links to navigate to related resources or child resources of the requested endpoint. The API supports the following media types for most endpoints:  `application/hal+json`, `application/json`, and `text/csv`.  For authentication, the API supports both `Basic` and `Bearer` HTTP authentication schemes.  To get started, create a session and receive credentials for `Basic` authentication by sending a `POST` request to the [/sessions](#/Admin%20Resources/postSession) endpoint, with a message body containing the user's credentials:  ```{\"username\":\"apiuser\", \"password\":\"apipass\"}```  The response will contain an `apiToken` field that can be entered with the username in the Swagger UI **Authorize** dialog. The response will also contain a `basicAuthenticationCredentials` field containing a base64 encoding of the requester's username and API token delimited by a colon. This string can be injected directly into request `Authorization` headers in the following format:  ```Authorization: Basic YXBpOlQ0OExOT3VIRGhDcnVBNEo1bGFES3JuS3hTZC9QK3pjczZXTzBJMDY=```  For full details on API format and authentication methods, refer to the Address Manager RESTful v2 API Guide on the BlueCat Documentation Portal.

API version: 9.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gobam2

import (
	"encoding/json"
)

// checks if the LinkedIPv4Address type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LinkedIPv4Address{}

// LinkedIPv4Address struct for LinkedIPv4Address
type LinkedIPv4Address struct {
	LinkedAddress
	// The type of IP address.
	Type *string `json:"type,omitempty"`
}

// NewLinkedIPv4Address instantiates a new LinkedIPv4Address object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLinkedIPv4Address() *LinkedIPv4Address {
	this := LinkedIPv4Address{}
	return &this
}

// NewLinkedIPv4AddressWithDefaults instantiates a new LinkedIPv4Address object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLinkedIPv4AddressWithDefaults() *LinkedIPv4Address {
	this := LinkedIPv4Address{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *LinkedIPv4Address) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinkedIPv4Address) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *LinkedIPv4Address) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *LinkedIPv4Address) SetType(v string) {
	o.Type = &v
}

func (o LinkedIPv4Address) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LinkedIPv4Address) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableLinkedIPv4Address struct {
	value *LinkedIPv4Address
	isSet bool
}

func (v NullableLinkedIPv4Address) Get() *LinkedIPv4Address {
	return v.value
}

func (v *NullableLinkedIPv4Address) Set(val *LinkedIPv4Address) {
	v.value = val
	v.isSet = true
}

func (v NullableLinkedIPv4Address) IsSet() bool {
	return v.isSet
}

func (v *NullableLinkedIPv4Address) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLinkedIPv4Address(val *LinkedIPv4Address) *NullableLinkedIPv4Address {
	return &NullableLinkedIPv4Address{value: val, isSet: true}
}

func (v NullableLinkedIPv4Address) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLinkedIPv4Address) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


