/*
BlueCat Address Manager 9.5 RESTful v2 API

The **BlueCat Address Manager 9.5 RESTful v2 API** is a new RESTful API for Address Manager that presents Address Manager objects as resources. Each resource has a unique endpoint, and related resources are grouped in collections. To fetch an individual resource, a `GET` request is sent to the resource's endpoint. To fetch all resources in a collection, a `GET` request is sent to the collection's endpoint.  The RESTful v2 API is [hypermedia driven](https://en.wikipedia.org/wiki/HATEOAS) and uses the [HAL](https://en.wikipedia.org/wiki/Hypertext_Application_Language) format for representing links. When navigating through the API, you can use those links to navigate to related resources or child resources of the requested endpoint. The API supports the following media types for most endpoints:  `application/hal+json`, `application/json`, and `text/csv`.  For authentication, the API supports both `Basic` and `Bearer` HTTP authentication schemes.  To get started, create a session and receive credentials for `Basic` authentication by sending a `POST` request to the [/sessions](#/Admin%20Resources/postSession) endpoint, with a message body containing the user's credentials:  ```{\"username\":\"apiuser\", \"password\":\"apipass\"}```  The response will contain an `apiToken` field that can be entered with the username in the Swagger UI **Authorize** dialog. The response will also contain a `basicAuthenticationCredentials` field containing a base64 encoding of the requester's username and API token delimited by a colon. This string can be injected directly into request `Authorization` headers in the following format:  ```Authorization: Basic YXBpOlQ0OExOT3VIRGhDcnVBNEo1bGFES3JuS3hTZC9QK3pjczZXTzBJMDY=```  For full details on API format and authentication methods, refer to the Address Manager RESTful v2 API Guide on the BlueCat Documentation Portal.

API version: 9.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gobam2

import (
	"encoding/json"
)

// checks if the KerberosServicePrincipal type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KerberosServicePrincipal{}

// KerberosServicePrincipal The security ticket for the DNS service to use to authenticate keys requested by the GSS-TSIG protocol.
type KerberosServicePrincipal struct {
	// The resource identifier.
	Id *int64 `json:"id,omitempty"`
	// The resource type.
	Type *string `json:"type,omitempty"`
	// The name for the Kerberos service principal defined in the User Logon name field in Windows configuration section.
	Name *string `json:"name,omitempty" validate:"regexp=^.*\\\\S+.*$"`
	// User-defined fields set for the resource.
	UserDefinedFields *map[string]string `json:"userDefinedFields,omitempty"`
	// The msDS-KeyVersionNumber attribute value displayed in ADSI Edit on the Windows DC for the principal’s Kerberos key.
	KeyVersionNumber *int32 `json:"keyVersionNumber,omitempty"`
	// The principal’s Kerberos password. This is the AD user account password created on Windows DC.
	Password *string `json:"password,omitempty" validate:"regexp=^.*\\\\S+.*$"`
}

// NewKerberosServicePrincipal instantiates a new KerberosServicePrincipal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKerberosServicePrincipal() *KerberosServicePrincipal {
	this := KerberosServicePrincipal{}
	return &this
}

// NewKerberosServicePrincipalWithDefaults instantiates a new KerberosServicePrincipal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKerberosServicePrincipalWithDefaults() *KerberosServicePrincipal {
	this := KerberosServicePrincipal{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *KerberosServicePrincipal) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosServicePrincipal) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *KerberosServicePrincipal) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *KerberosServicePrincipal) SetId(v int64) {
	o.Id = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *KerberosServicePrincipal) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosServicePrincipal) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *KerberosServicePrincipal) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *KerberosServicePrincipal) SetType(v string) {
	o.Type = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *KerberosServicePrincipal) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosServicePrincipal) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *KerberosServicePrincipal) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *KerberosServicePrincipal) SetName(v string) {
	o.Name = &v
}

// GetUserDefinedFields returns the UserDefinedFields field value if set, zero value otherwise.
func (o *KerberosServicePrincipal) GetUserDefinedFields() map[string]string {
	if o == nil || IsNil(o.UserDefinedFields) {
		var ret map[string]string
		return ret
	}
	return *o.UserDefinedFields
}

// GetUserDefinedFieldsOk returns a tuple with the UserDefinedFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosServicePrincipal) GetUserDefinedFieldsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.UserDefinedFields) {
		return nil, false
	}
	return o.UserDefinedFields, true
}

// HasUserDefinedFields returns a boolean if a field has been set.
func (o *KerberosServicePrincipal) HasUserDefinedFields() bool {
	if o != nil && !IsNil(o.UserDefinedFields) {
		return true
	}

	return false
}

// SetUserDefinedFields gets a reference to the given map[string]string and assigns it to the UserDefinedFields field.
func (o *KerberosServicePrincipal) SetUserDefinedFields(v map[string]string) {
	o.UserDefinedFields = &v
}

// GetKeyVersionNumber returns the KeyVersionNumber field value if set, zero value otherwise.
func (o *KerberosServicePrincipal) GetKeyVersionNumber() int32 {
	if o == nil || IsNil(o.KeyVersionNumber) {
		var ret int32
		return ret
	}
	return *o.KeyVersionNumber
}

// GetKeyVersionNumberOk returns a tuple with the KeyVersionNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosServicePrincipal) GetKeyVersionNumberOk() (*int32, bool) {
	if o == nil || IsNil(o.KeyVersionNumber) {
		return nil, false
	}
	return o.KeyVersionNumber, true
}

// HasKeyVersionNumber returns a boolean if a field has been set.
func (o *KerberosServicePrincipal) HasKeyVersionNumber() bool {
	if o != nil && !IsNil(o.KeyVersionNumber) {
		return true
	}

	return false
}

// SetKeyVersionNumber gets a reference to the given int32 and assigns it to the KeyVersionNumber field.
func (o *KerberosServicePrincipal) SetKeyVersionNumber(v int32) {
	o.KeyVersionNumber = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *KerberosServicePrincipal) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KerberosServicePrincipal) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *KerberosServicePrincipal) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *KerberosServicePrincipal) SetPassword(v string) {
	o.Password = &v
}

func (o KerberosServicePrincipal) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KerberosServicePrincipal) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.UserDefinedFields) {
		toSerialize["userDefinedFields"] = o.UserDefinedFields
	}
	if !IsNil(o.KeyVersionNumber) {
		toSerialize["keyVersionNumber"] = o.KeyVersionNumber
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	return toSerialize, nil
}

type NullableKerberosServicePrincipal struct {
	value *KerberosServicePrincipal
	isSet bool
}

func (v NullableKerberosServicePrincipal) Get() *KerberosServicePrincipal {
	return v.value
}

func (v *NullableKerberosServicePrincipal) Set(val *KerberosServicePrincipal) {
	v.value = val
	v.isSet = true
}

func (v NullableKerberosServicePrincipal) IsSet() bool {
	return v.isSet
}

func (v *NullableKerberosServicePrincipal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKerberosServicePrincipal(val *KerberosServicePrincipal) *NullableKerberosServicePrincipal {
	return &NullableKerberosServicePrincipal{value: val, isSet: true}
}

func (v NullableKerberosServicePrincipal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKerberosServicePrincipal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


