/*
BlueCat Address Manager 9.5 RESTful v2 API

The **BlueCat Address Manager 9.5 RESTful v2 API** is a new RESTful API for Address Manager that presents Address Manager objects as resources. Each resource has a unique endpoint, and related resources are grouped in collections. To fetch an individual resource, a `GET` request is sent to the resource's endpoint. To fetch all resources in a collection, a `GET` request is sent to the collection's endpoint.  The RESTful v2 API is [hypermedia driven](https://en.wikipedia.org/wiki/HATEOAS) and uses the [HAL](https://en.wikipedia.org/wiki/Hypertext_Application_Language) format for representing links. When navigating through the API, you can use those links to navigate to related resources or child resources of the requested endpoint. The API supports the following media types for most endpoints:  `application/hal+json`, `application/json`, and `text/csv`.  For authentication, the API supports both `Basic` and `Bearer` HTTP authentication schemes.  To get started, create a session and receive credentials for `Basic` authentication by sending a `POST` request to the [/sessions](#/Admin%20Resources/postSession) endpoint, with a message body containing the user's credentials:  ```{\"username\":\"apiuser\", \"password\":\"apipass\"}```  The response will contain an `apiToken` field that can be entered with the username in the Swagger UI **Authorize** dialog. The response will also contain a `basicAuthenticationCredentials` field containing a base64 encoding of the requester's username and API token delimited by a colon. This string can be injected directly into request `Authorization` headers in the following format:  ```Authorization: Basic YXBpOlQ0OExOT3VIRGhDcnVBNEo1bGFES3JuS3hTZC9QK3pjczZXTzBJMDY=```  For full details on API format and authentication methods, refer to the Address Manager RESTful v2 API Guide on the BlueCat Documentation Portal.

API version: 9.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gobam2

import (
	"encoding/json"
)

// checks if the IPv4BlockMerge type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IPv4BlockMerge{}

// IPv4BlockMerge struct for IPv4BlockMerge
type IPv4BlockMerge struct {
	Merge
	// The resource type.
	Type *string `json:"type,omitempty"`
	Blocks []IPv4BlockMergeAllOfBlocks `json:"blocks,omitempty"`
	Destination *InlinedIpv4BlockMergeDestination `json:"destination,omitempty"`
}

// NewIPv4BlockMerge instantiates a new IPv4BlockMerge object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIPv4BlockMerge() *IPv4BlockMerge {
	this := IPv4BlockMerge{}
	return &this
}

// NewIPv4BlockMergeWithDefaults instantiates a new IPv4BlockMerge object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIPv4BlockMergeWithDefaults() *IPv4BlockMerge {
	this := IPv4BlockMerge{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *IPv4BlockMerge) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPv4BlockMerge) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *IPv4BlockMerge) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *IPv4BlockMerge) SetType(v string) {
	o.Type = &v
}

// GetBlocks returns the Blocks field value if set, zero value otherwise.
func (o *IPv4BlockMerge) GetBlocks() []IPv4BlockMergeAllOfBlocks {
	if o == nil || IsNil(o.Blocks) {
		var ret []IPv4BlockMergeAllOfBlocks
		return ret
	}
	return o.Blocks
}

// GetBlocksOk returns a tuple with the Blocks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPv4BlockMerge) GetBlocksOk() ([]IPv4BlockMergeAllOfBlocks, bool) {
	if o == nil || IsNil(o.Blocks) {
		return nil, false
	}
	return o.Blocks, true
}

// HasBlocks returns a boolean if a field has been set.
func (o *IPv4BlockMerge) HasBlocks() bool {
	if o != nil && !IsNil(o.Blocks) {
		return true
	}

	return false
}

// SetBlocks gets a reference to the given []IPv4BlockMergeAllOfBlocks and assigns it to the Blocks field.
func (o *IPv4BlockMerge) SetBlocks(v []IPv4BlockMergeAllOfBlocks) {
	o.Blocks = v
}

// GetDestination returns the Destination field value if set, zero value otherwise.
func (o *IPv4BlockMerge) GetDestination() InlinedIpv4BlockMergeDestination {
	if o == nil || IsNil(o.Destination) {
		var ret InlinedIpv4BlockMergeDestination
		return ret
	}
	return *o.Destination
}

// GetDestinationOk returns a tuple with the Destination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPv4BlockMerge) GetDestinationOk() (*InlinedIpv4BlockMergeDestination, bool) {
	if o == nil || IsNil(o.Destination) {
		return nil, false
	}
	return o.Destination, true
}

// HasDestination returns a boolean if a field has been set.
func (o *IPv4BlockMerge) HasDestination() bool {
	if o != nil && !IsNil(o.Destination) {
		return true
	}

	return false
}

// SetDestination gets a reference to the given InlinedIpv4BlockMergeDestination and assigns it to the Destination field.
func (o *IPv4BlockMerge) SetDestination(v InlinedIpv4BlockMergeDestination) {
	o.Destination = &v
}

func (o IPv4BlockMerge) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IPv4BlockMerge) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Blocks) {
		toSerialize["blocks"] = o.Blocks
	}
	if !IsNil(o.Destination) {
		toSerialize["destination"] = o.Destination
	}
	return toSerialize, nil
}

type NullableIPv4BlockMerge struct {
	value *IPv4BlockMerge
	isSet bool
}

func (v NullableIPv4BlockMerge) Get() *IPv4BlockMerge {
	return v.value
}

func (v *NullableIPv4BlockMerge) Set(val *IPv4BlockMerge) {
	v.value = val
	v.isSet = true
}

func (v NullableIPv4BlockMerge) IsSet() bool {
	return v.isSet
}

func (v *NullableIPv4BlockMerge) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIPv4BlockMerge(val *IPv4BlockMerge) *NullableIPv4BlockMerge {
	return &NullableIPv4BlockMerge{value: val, isSet: true}
}

func (v NullableIPv4BlockMerge) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIPv4BlockMerge) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


