/*
BlueCat Address Manager 9.5 RESTful v2 API

The **BlueCat Address Manager 9.5 RESTful v2 API** is a new RESTful API for Address Manager that presents Address Manager objects as resources. Each resource has a unique endpoint, and related resources are grouped in collections. To fetch an individual resource, a `GET` request is sent to the resource's endpoint. To fetch all resources in a collection, a `GET` request is sent to the collection's endpoint.  The RESTful v2 API is [hypermedia driven](https://en.wikipedia.org/wiki/HATEOAS) and uses the [HAL](https://en.wikipedia.org/wiki/Hypertext_Application_Language) format for representing links. When navigating through the API, you can use those links to navigate to related resources or child resources of the requested endpoint. The API supports the following media types for most endpoints:  `application/hal+json`, `application/json`, and `text/csv`.  For authentication, the API supports both `Basic` and `Bearer` HTTP authentication schemes.  To get started, create a session and receive credentials for `Basic` authentication by sending a `POST` request to the [/sessions](#/Admin%20Resources/postSession) endpoint, with a message body containing the user's credentials:  ```{\"username\":\"apiuser\", \"password\":\"apipass\"}```  The response will contain an `apiToken` field that can be entered with the username in the Swagger UI **Authorize** dialog. The response will also contain a `basicAuthenticationCredentials` field containing a base64 encoding of the requester's username and API token delimited by a colon. This string can be injected directly into request `Authorization` headers in the following format:  ```Authorization: Basic YXBpOlQ0OExOT3VIRGhDcnVBNEo1bGFES3JuS3hTZC9QK3pjczZXTzBJMDY=```  For full details on API format and authentication methods, refer to the Address Manager RESTful v2 API Guide on the BlueCat Documentation Portal.

API version: 9.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gobam2

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// PutZoneRequest - struct for PutZoneRequest
type PutZoneRequest struct {
	ENUMNumberZonePutRequestBody *ENUMNumberZonePutRequestBody
	ENUMZonePutRequestBody *ENUMZonePutRequestBody
	InternalRootZonePutRequestBody *InternalRootZonePutRequestBody
	ResponsePolicyZonePutRequestBody *ResponsePolicyZonePutRequestBody
	ZonePutRequestBody *ZonePutRequestBody
}

// ENUMNumberZonePutRequestBodyAsPutZoneRequest is a convenience function that returns ENUMNumberZonePutRequestBody wrapped in PutZoneRequest
func ENUMNumberZonePutRequestBodyAsPutZoneRequest(v *ENUMNumberZonePutRequestBody) PutZoneRequest {
	return PutZoneRequest{
		ENUMNumberZonePutRequestBody: v,
	}
}

// ENUMZonePutRequestBodyAsPutZoneRequest is a convenience function that returns ENUMZonePutRequestBody wrapped in PutZoneRequest
func ENUMZonePutRequestBodyAsPutZoneRequest(v *ENUMZonePutRequestBody) PutZoneRequest {
	return PutZoneRequest{
		ENUMZonePutRequestBody: v,
	}
}

// InternalRootZonePutRequestBodyAsPutZoneRequest is a convenience function that returns InternalRootZonePutRequestBody wrapped in PutZoneRequest
func InternalRootZonePutRequestBodyAsPutZoneRequest(v *InternalRootZonePutRequestBody) PutZoneRequest {
	return PutZoneRequest{
		InternalRootZonePutRequestBody: v,
	}
}

// ResponsePolicyZonePutRequestBodyAsPutZoneRequest is a convenience function that returns ResponsePolicyZonePutRequestBody wrapped in PutZoneRequest
func ResponsePolicyZonePutRequestBodyAsPutZoneRequest(v *ResponsePolicyZonePutRequestBody) PutZoneRequest {
	return PutZoneRequest{
		ResponsePolicyZonePutRequestBody: v,
	}
}

// ZonePutRequestBodyAsPutZoneRequest is a convenience function that returns ZonePutRequestBody wrapped in PutZoneRequest
func ZonePutRequestBodyAsPutZoneRequest(v *ZonePutRequestBody) PutZoneRequest {
	return PutZoneRequest{
		ZonePutRequestBody: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *PutZoneRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ENUMNumberZonePutRequestBody
	err = newStrictDecoder(data).Decode(&dst.ENUMNumberZonePutRequestBody)
	if err == nil {
		jsonENUMNumberZonePutRequestBody, _ := json.Marshal(dst.ENUMNumberZonePutRequestBody)
		if string(jsonENUMNumberZonePutRequestBody) == "{}" { // empty struct
			dst.ENUMNumberZonePutRequestBody = nil
		} else {
			if err = validator.Validate(dst.ENUMNumberZonePutRequestBody); err != nil {
				dst.ENUMNumberZonePutRequestBody = nil
			} else {
				match++
			}
		}
	} else {
		dst.ENUMNumberZonePutRequestBody = nil
	}

	// try to unmarshal data into ENUMZonePutRequestBody
	err = newStrictDecoder(data).Decode(&dst.ENUMZonePutRequestBody)
	if err == nil {
		jsonENUMZonePutRequestBody, _ := json.Marshal(dst.ENUMZonePutRequestBody)
		if string(jsonENUMZonePutRequestBody) == "{}" { // empty struct
			dst.ENUMZonePutRequestBody = nil
		} else {
			if err = validator.Validate(dst.ENUMZonePutRequestBody); err != nil {
				dst.ENUMZonePutRequestBody = nil
			} else {
				match++
			}
		}
	} else {
		dst.ENUMZonePutRequestBody = nil
	}

	// try to unmarshal data into InternalRootZonePutRequestBody
	err = newStrictDecoder(data).Decode(&dst.InternalRootZonePutRequestBody)
	if err == nil {
		jsonInternalRootZonePutRequestBody, _ := json.Marshal(dst.InternalRootZonePutRequestBody)
		if string(jsonInternalRootZonePutRequestBody) == "{}" { // empty struct
			dst.InternalRootZonePutRequestBody = nil
		} else {
			if err = validator.Validate(dst.InternalRootZonePutRequestBody); err != nil {
				dst.InternalRootZonePutRequestBody = nil
			} else {
				match++
			}
		}
	} else {
		dst.InternalRootZonePutRequestBody = nil
	}

	// try to unmarshal data into ResponsePolicyZonePutRequestBody
	err = newStrictDecoder(data).Decode(&dst.ResponsePolicyZonePutRequestBody)
	if err == nil {
		jsonResponsePolicyZonePutRequestBody, _ := json.Marshal(dst.ResponsePolicyZonePutRequestBody)
		if string(jsonResponsePolicyZonePutRequestBody) == "{}" { // empty struct
			dst.ResponsePolicyZonePutRequestBody = nil
		} else {
			if err = validator.Validate(dst.ResponsePolicyZonePutRequestBody); err != nil {
				dst.ResponsePolicyZonePutRequestBody = nil
			} else {
				match++
			}
		}
	} else {
		dst.ResponsePolicyZonePutRequestBody = nil
	}

	// try to unmarshal data into ZonePutRequestBody
	err = newStrictDecoder(data).Decode(&dst.ZonePutRequestBody)
	if err == nil {
		jsonZonePutRequestBody, _ := json.Marshal(dst.ZonePutRequestBody)
		if string(jsonZonePutRequestBody) == "{}" { // empty struct
			dst.ZonePutRequestBody = nil
		} else {
			if err = validator.Validate(dst.ZonePutRequestBody); err != nil {
				dst.ZonePutRequestBody = nil
			} else {
				match++
			}
		}
	} else {
		dst.ZonePutRequestBody = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ENUMNumberZonePutRequestBody = nil
		dst.ENUMZonePutRequestBody = nil
		dst.InternalRootZonePutRequestBody = nil
		dst.ResponsePolicyZonePutRequestBody = nil
		dst.ZonePutRequestBody = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PutZoneRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PutZoneRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PutZoneRequest) MarshalJSON() ([]byte, error) {
	if src.ENUMNumberZonePutRequestBody != nil {
		return json.Marshal(&src.ENUMNumberZonePutRequestBody)
	}

	if src.ENUMZonePutRequestBody != nil {
		return json.Marshal(&src.ENUMZonePutRequestBody)
	}

	if src.InternalRootZonePutRequestBody != nil {
		return json.Marshal(&src.InternalRootZonePutRequestBody)
	}

	if src.ResponsePolicyZonePutRequestBody != nil {
		return json.Marshal(&src.ResponsePolicyZonePutRequestBody)
	}

	if src.ZonePutRequestBody != nil {
		return json.Marshal(&src.ZonePutRequestBody)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PutZoneRequest) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ENUMNumberZonePutRequestBody != nil {
		return obj.ENUMNumberZonePutRequestBody
	}

	if obj.ENUMZonePutRequestBody != nil {
		return obj.ENUMZonePutRequestBody
	}

	if obj.InternalRootZonePutRequestBody != nil {
		return obj.InternalRootZonePutRequestBody
	}

	if obj.ResponsePolicyZonePutRequestBody != nil {
		return obj.ResponsePolicyZonePutRequestBody
	}

	if obj.ZonePutRequestBody != nil {
		return obj.ZonePutRequestBody
	}

	// all schemas are nil
	return nil
}

type NullablePutZoneRequest struct {
	value *PutZoneRequest
	isSet bool
}

func (v NullablePutZoneRequest) Get() *PutZoneRequest {
	return v.value
}

func (v *NullablePutZoneRequest) Set(val *PutZoneRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePutZoneRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePutZoneRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePutZoneRequest(val *PutZoneRequest) *NullablePutZoneRequest {
	return &NullablePutZoneRequest{value: val, isSet: true}
}

func (v NullablePutZoneRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePutZoneRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


