/*
BlueCat Address Manager 9.5 RESTful v2 API

The **BlueCat Address Manager 9.5 RESTful v2 API** is a new RESTful API for Address Manager that presents Address Manager objects as resources. Each resource has a unique endpoint, and related resources are grouped in collections. To fetch an individual resource, a `GET` request is sent to the resource's endpoint. To fetch all resources in a collection, a `GET` request is sent to the collection's endpoint.  The RESTful v2 API is [hypermedia driven](https://en.wikipedia.org/wiki/HATEOAS) and uses the [HAL](https://en.wikipedia.org/wiki/Hypertext_Application_Language) format for representing links. When navigating through the API, you can use those links to navigate to related resources or child resources of the requested endpoint. The API supports the following media types for most endpoints:  `application/hal+json`, `application/json`, and `text/csv`.  For authentication, the API supports both `Basic` and `Bearer` HTTP authentication schemes.  To get started, create a session and receive credentials for `Basic` authentication by sending a `POST` request to the [/sessions](#/Admin%20Resources/postSession) endpoint, with a message body containing the user's credentials:  ```{\"username\":\"apiuser\", \"password\":\"apipass\"}```  The response will contain an `apiToken` field that can be entered with the username in the Swagger UI **Authorize** dialog. The response will also contain a `basicAuthenticationCredentials` field containing a base64 encoding of the requester's username and API token delimited by a colon. This string can be injected directly into request `Authorization` headers in the following format:  ```Authorization: Basic YXBpOlQ0OExOT3VIRGhDcnVBNEo1bGFES3JuS3hTZC9QK3pjczZXTzBJMDY=```  For full details on API format and authentication methods, refer to the Address Manager RESTful v2 API Guide on the BlueCat Documentation Portal.

API version: 9.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gobam2

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// GetBlocks200Response1DataInner - struct for GetBlocks200Response1DataInner
type GetBlocks200Response1DataInner struct {
	IPv4Block *IPv4Block
	IPv6Block *IPv6Block
}

// IPv4BlockAsGetBlocks200Response1DataInner is a convenience function that returns IPv4Block wrapped in GetBlocks200Response1DataInner
func IPv4BlockAsGetBlocks200Response1DataInner(v *IPv4Block) GetBlocks200Response1DataInner {
	return GetBlocks200Response1DataInner{
		IPv4Block: v,
	}
}

// IPv6BlockAsGetBlocks200Response1DataInner is a convenience function that returns IPv6Block wrapped in GetBlocks200Response1DataInner
func IPv6BlockAsGetBlocks200Response1DataInner(v *IPv6Block) GetBlocks200Response1DataInner {
	return GetBlocks200Response1DataInner{
		IPv6Block: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *GetBlocks200Response1DataInner) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into IPv4Block
	err = newStrictDecoder(data).Decode(&dst.IPv4Block)
	if err == nil {
		jsonIPv4Block, _ := json.Marshal(dst.IPv4Block)
		if string(jsonIPv4Block) == "{}" { // empty struct
			dst.IPv4Block = nil
		} else {
			if err = validator.Validate(dst.IPv4Block); err != nil {
				dst.IPv4Block = nil
			} else {
				match++
			}
		}
	} else {
		dst.IPv4Block = nil
	}

	// try to unmarshal data into IPv6Block
	err = newStrictDecoder(data).Decode(&dst.IPv6Block)
	if err == nil {
		jsonIPv6Block, _ := json.Marshal(dst.IPv6Block)
		if string(jsonIPv6Block) == "{}" { // empty struct
			dst.IPv6Block = nil
		} else {
			if err = validator.Validate(dst.IPv6Block); err != nil {
				dst.IPv6Block = nil
			} else {
				match++
			}
		}
	} else {
		dst.IPv6Block = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.IPv4Block = nil
		dst.IPv6Block = nil

		return fmt.Errorf("data matches more than one schema in oneOf(GetBlocks200Response1DataInner)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(GetBlocks200Response1DataInner)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetBlocks200Response1DataInner) MarshalJSON() ([]byte, error) {
	if src.IPv4Block != nil {
		return json.Marshal(&src.IPv4Block)
	}

	if src.IPv6Block != nil {
		return json.Marshal(&src.IPv6Block)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *GetBlocks200Response1DataInner) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.IPv4Block != nil {
		return obj.IPv4Block
	}

	if obj.IPv6Block != nil {
		return obj.IPv6Block
	}

	// all schemas are nil
	return nil
}

type NullableGetBlocks200Response1DataInner struct {
	value *GetBlocks200Response1DataInner
	isSet bool
}

func (v NullableGetBlocks200Response1DataInner) Get() *GetBlocks200Response1DataInner {
	return v.value
}

func (v *NullableGetBlocks200Response1DataInner) Set(val *GetBlocks200Response1DataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetBlocks200Response1DataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetBlocks200Response1DataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetBlocks200Response1DataInner(val *GetBlocks200Response1DataInner) *NullableGetBlocks200Response1DataInner {
	return &NullableGetBlocks200Response1DataInner{value: val, isSet: true}
}

func (v NullableGetBlocks200Response1DataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetBlocks200Response1DataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


