/*
BlueCat Address Manager 9.5 RESTful v2 API

The **BlueCat Address Manager 9.5 RESTful v2 API** is a new RESTful API for Address Manager that presents Address Manager objects as resources. Each resource has a unique endpoint, and related resources are grouped in collections. To fetch an individual resource, a `GET` request is sent to the resource's endpoint. To fetch all resources in a collection, a `GET` request is sent to the collection's endpoint.  The RESTful v2 API is [hypermedia driven](https://en.wikipedia.org/wiki/HATEOAS) and uses the [HAL](https://en.wikipedia.org/wiki/Hypertext_Application_Language) format for representing links. When navigating through the API, you can use those links to navigate to related resources or child resources of the requested endpoint. The API supports the following media types for most endpoints:  `application/hal+json`, `application/json`, and `text/csv`.  For authentication, the API supports both `Basic` and `Bearer` HTTP authentication schemes.  To get started, create a session and receive credentials for `Basic` authentication by sending a `POST` request to the [/sessions](#/Admin%20Resources/postSession) endpoint, with a message body containing the user's credentials:  ```{\"username\":\"apiuser\", \"password\":\"apipass\"}```  The response will contain an `apiToken` field that can be entered with the username in the Swagger UI **Authorize** dialog. The response will also contain a `basicAuthenticationCredentials` field containing a base64 encoding of the requester's username and API token delimited by a colon. This string can be injected directly into request `Authorization` headers in the following format:  ```Authorization: Basic YXBpOlQ0OExOT3VIRGhDcnVBNEo1bGFES3JuS3hTZC9QK3pjczZXTzBJMDY=```  For full details on API format and authentication methods, refer to the Address Manager RESTful v2 API Guide on the BlueCat Documentation Portal.

API version: 9.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gobam2

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// GetMerges200Response1DataInner - struct for GetMerges200Response1DataInner
type GetMerges200Response1DataInner struct {
	IPv4BlockMerge *IPv4BlockMerge
	IPv4DHCPRangeMerge *IPv4DHCPRangeMerge
	IPv4NetworkMerge *IPv4NetworkMerge
}

// IPv4BlockMergeAsGetMerges200Response1DataInner is a convenience function that returns IPv4BlockMerge wrapped in GetMerges200Response1DataInner
func IPv4BlockMergeAsGetMerges200Response1DataInner(v *IPv4BlockMerge) GetMerges200Response1DataInner {
	return GetMerges200Response1DataInner{
		IPv4BlockMerge: v,
	}
}

// IPv4DHCPRangeMergeAsGetMerges200Response1DataInner is a convenience function that returns IPv4DHCPRangeMerge wrapped in GetMerges200Response1DataInner
func IPv4DHCPRangeMergeAsGetMerges200Response1DataInner(v *IPv4DHCPRangeMerge) GetMerges200Response1DataInner {
	return GetMerges200Response1DataInner{
		IPv4DHCPRangeMerge: v,
	}
}

// IPv4NetworkMergeAsGetMerges200Response1DataInner is a convenience function that returns IPv4NetworkMerge wrapped in GetMerges200Response1DataInner
func IPv4NetworkMergeAsGetMerges200Response1DataInner(v *IPv4NetworkMerge) GetMerges200Response1DataInner {
	return GetMerges200Response1DataInner{
		IPv4NetworkMerge: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *GetMerges200Response1DataInner) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into IPv4BlockMerge
	err = newStrictDecoder(data).Decode(&dst.IPv4BlockMerge)
	if err == nil {
		jsonIPv4BlockMerge, _ := json.Marshal(dst.IPv4BlockMerge)
		if string(jsonIPv4BlockMerge) == "{}" { // empty struct
			dst.IPv4BlockMerge = nil
		} else {
			if err = validator.Validate(dst.IPv4BlockMerge); err != nil {
				dst.IPv4BlockMerge = nil
			} else {
				match++
			}
		}
	} else {
		dst.IPv4BlockMerge = nil
	}

	// try to unmarshal data into IPv4DHCPRangeMerge
	err = newStrictDecoder(data).Decode(&dst.IPv4DHCPRangeMerge)
	if err == nil {
		jsonIPv4DHCPRangeMerge, _ := json.Marshal(dst.IPv4DHCPRangeMerge)
		if string(jsonIPv4DHCPRangeMerge) == "{}" { // empty struct
			dst.IPv4DHCPRangeMerge = nil
		} else {
			if err = validator.Validate(dst.IPv4DHCPRangeMerge); err != nil {
				dst.IPv4DHCPRangeMerge = nil
			} else {
				match++
			}
		}
	} else {
		dst.IPv4DHCPRangeMerge = nil
	}

	// try to unmarshal data into IPv4NetworkMerge
	err = newStrictDecoder(data).Decode(&dst.IPv4NetworkMerge)
	if err == nil {
		jsonIPv4NetworkMerge, _ := json.Marshal(dst.IPv4NetworkMerge)
		if string(jsonIPv4NetworkMerge) == "{}" { // empty struct
			dst.IPv4NetworkMerge = nil
		} else {
			if err = validator.Validate(dst.IPv4NetworkMerge); err != nil {
				dst.IPv4NetworkMerge = nil
			} else {
				match++
			}
		}
	} else {
		dst.IPv4NetworkMerge = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.IPv4BlockMerge = nil
		dst.IPv4DHCPRangeMerge = nil
		dst.IPv4NetworkMerge = nil

		return fmt.Errorf("data matches more than one schema in oneOf(GetMerges200Response1DataInner)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(GetMerges200Response1DataInner)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetMerges200Response1DataInner) MarshalJSON() ([]byte, error) {
	if src.IPv4BlockMerge != nil {
		return json.Marshal(&src.IPv4BlockMerge)
	}

	if src.IPv4DHCPRangeMerge != nil {
		return json.Marshal(&src.IPv4DHCPRangeMerge)
	}

	if src.IPv4NetworkMerge != nil {
		return json.Marshal(&src.IPv4NetworkMerge)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *GetMerges200Response1DataInner) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.IPv4BlockMerge != nil {
		return obj.IPv4BlockMerge
	}

	if obj.IPv4DHCPRangeMerge != nil {
		return obj.IPv4DHCPRangeMerge
	}

	if obj.IPv4NetworkMerge != nil {
		return obj.IPv4NetworkMerge
	}

	// all schemas are nil
	return nil
}

type NullableGetMerges200Response1DataInner struct {
	value *GetMerges200Response1DataInner
	isSet bool
}

func (v NullableGetMerges200Response1DataInner) Get() *GetMerges200Response1DataInner {
	return v.value
}

func (v *NullableGetMerges200Response1DataInner) Set(val *GetMerges200Response1DataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMerges200Response1DataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMerges200Response1DataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMerges200Response1DataInner(val *GetMerges200Response1DataInner) *NullableGetMerges200Response1DataInner {
	return &NullableGetMerges200Response1DataInner{value: val, isSet: true}
}

func (v NullableGetMerges200Response1DataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMerges200Response1DataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


