/*
BlueCat Address Manager 9.5 RESTful v2 API

The **BlueCat Address Manager 9.5 RESTful v2 API** is a new RESTful API for Address Manager that presents Address Manager objects as resources. Each resource has a unique endpoint, and related resources are grouped in collections. To fetch an individual resource, a `GET` request is sent to the resource's endpoint. To fetch all resources in a collection, a `GET` request is sent to the collection's endpoint.  The RESTful v2 API is [hypermedia driven](https://en.wikipedia.org/wiki/HATEOAS) and uses the [HAL](https://en.wikipedia.org/wiki/Hypertext_Application_Language) format for representing links. When navigating through the API, you can use those links to navigate to related resources or child resources of the requested endpoint. The API supports the following media types for most endpoints:  `application/hal+json`, `application/json`, and `text/csv`.  For authentication, the API supports both `Basic` and `Bearer` HTTP authentication schemes.  To get started, create a session and receive credentials for `Basic` authentication by sending a `POST` request to the [/sessions](#/Admin%20Resources/postSession) endpoint, with a message body containing the user's credentials:  ```{\"username\":\"apiuser\", \"password\":\"apipass\"}```  The response will contain an `apiToken` field that can be entered with the username in the Swagger UI **Authorize** dialog. The response will also contain a `basicAuthenticationCredentials` field containing a base64 encoding of the requester's username and API token delimited by a colon. This string can be injected directly into request `Authorization` headers in the following format:  ```Authorization: Basic YXBpOlQ0OExOT3VIRGhDcnVBNEo1bGFES3JuS3hTZC9QK3pjczZXTzBJMDY=```  For full details on API format and authentication methods, refer to the Address Manager RESTful v2 API Guide on the BlueCat Documentation Portal.

API version: 9.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gobam2

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the TrustRelationshipPostRequestBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrustRelationshipPostRequestBody{}

// TrustRelationshipPostRequestBody struct for TrustRelationshipPostRequestBody
type TrustRelationshipPostRequestBody struct {
	// The resource identifier.
	Id *int64 `json:"id,omitempty"`
	// The resource type.
	Type *string `json:"type,omitempty"`
	// The IP address of the remote Address Manager server that is part of the trust relationship.
	Address string `json:"address"`
	// The API username of the remote Address Manager server that is used to establish the trust relationship.
	Username string `json:"username" validate:"regexp=^.*\\\\S+.*$"`
	// The password of the API user that is used to establish the trust relationship with the remote Address Manager server.
	Password string `json:"password" validate:"regexp=^.*\\\\S+.*$"`
	// The timestamp of when the SSH key was created for exchange with the remote Address Manager server to establish the trust relationship.
	KeyGenerationDateTime *time.Time `json:"keyGenerationDateTime,omitempty"`
	// The state of the trust relationship.
	State *string `json:"state,omitempty"`
}

type _TrustRelationshipPostRequestBody TrustRelationshipPostRequestBody

// NewTrustRelationshipPostRequestBody instantiates a new TrustRelationshipPostRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrustRelationshipPostRequestBody(address string, username string, password string) *TrustRelationshipPostRequestBody {
	this := TrustRelationshipPostRequestBody{}
	this.Address = address
	this.Username = username
	this.Password = password
	return &this
}

// NewTrustRelationshipPostRequestBodyWithDefaults instantiates a new TrustRelationshipPostRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrustRelationshipPostRequestBodyWithDefaults() *TrustRelationshipPostRequestBody {
	this := TrustRelationshipPostRequestBody{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TrustRelationshipPostRequestBody) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrustRelationshipPostRequestBody) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *TrustRelationshipPostRequestBody) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *TrustRelationshipPostRequestBody) SetId(v int64) {
	o.Id = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *TrustRelationshipPostRequestBody) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrustRelationshipPostRequestBody) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *TrustRelationshipPostRequestBody) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *TrustRelationshipPostRequestBody) SetType(v string) {
	o.Type = &v
}

// GetAddress returns the Address field value
func (o *TrustRelationshipPostRequestBody) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *TrustRelationshipPostRequestBody) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *TrustRelationshipPostRequestBody) SetAddress(v string) {
	o.Address = v
}

// GetUsername returns the Username field value
func (o *TrustRelationshipPostRequestBody) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *TrustRelationshipPostRequestBody) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *TrustRelationshipPostRequestBody) SetUsername(v string) {
	o.Username = v
}

// GetPassword returns the Password field value
func (o *TrustRelationshipPostRequestBody) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *TrustRelationshipPostRequestBody) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *TrustRelationshipPostRequestBody) SetPassword(v string) {
	o.Password = v
}

// GetKeyGenerationDateTime returns the KeyGenerationDateTime field value if set, zero value otherwise.
func (o *TrustRelationshipPostRequestBody) GetKeyGenerationDateTime() time.Time {
	if o == nil || IsNil(o.KeyGenerationDateTime) {
		var ret time.Time
		return ret
	}
	return *o.KeyGenerationDateTime
}

// GetKeyGenerationDateTimeOk returns a tuple with the KeyGenerationDateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrustRelationshipPostRequestBody) GetKeyGenerationDateTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.KeyGenerationDateTime) {
		return nil, false
	}
	return o.KeyGenerationDateTime, true
}

// HasKeyGenerationDateTime returns a boolean if a field has been set.
func (o *TrustRelationshipPostRequestBody) HasKeyGenerationDateTime() bool {
	if o != nil && !IsNil(o.KeyGenerationDateTime) {
		return true
	}

	return false
}

// SetKeyGenerationDateTime gets a reference to the given time.Time and assigns it to the KeyGenerationDateTime field.
func (o *TrustRelationshipPostRequestBody) SetKeyGenerationDateTime(v time.Time) {
	o.KeyGenerationDateTime = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *TrustRelationshipPostRequestBody) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrustRelationshipPostRequestBody) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *TrustRelationshipPostRequestBody) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *TrustRelationshipPostRequestBody) SetState(v string) {
	o.State = &v
}

func (o TrustRelationshipPostRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrustRelationshipPostRequestBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	toSerialize["address"] = o.Address
	toSerialize["username"] = o.Username
	toSerialize["password"] = o.Password
	if !IsNil(o.KeyGenerationDateTime) {
		toSerialize["keyGenerationDateTime"] = o.KeyGenerationDateTime
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	return toSerialize, nil
}

func (o *TrustRelationshipPostRequestBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
		"username",
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTrustRelationshipPostRequestBody := _TrustRelationshipPostRequestBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTrustRelationshipPostRequestBody)

	if err != nil {
		return err
	}

	*o = TrustRelationshipPostRequestBody(varTrustRelationshipPostRequestBody)

	return err
}

type NullableTrustRelationshipPostRequestBody struct {
	value *TrustRelationshipPostRequestBody
	isSet bool
}

func (v NullableTrustRelationshipPostRequestBody) Get() *TrustRelationshipPostRequestBody {
	return v.value
}

func (v *NullableTrustRelationshipPostRequestBody) Set(val *TrustRelationshipPostRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableTrustRelationshipPostRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableTrustRelationshipPostRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrustRelationshipPostRequestBody(val *TrustRelationshipPostRequestBody) *NullableTrustRelationshipPostRequestBody {
	return &NullableTrustRelationshipPostRequestBody{value: val, isSet: true}
}

func (v NullableTrustRelationshipPostRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrustRelationshipPostRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


